import ReactMarkdown, { type Components } from "react-markdown";

/** Represents a single step in the instruction panel */
interface InstructionStep {
  icon: string; // emoji or icon for the step
  text: string; // step description (supports Markdown)
}

/** Props for InstructionPanel component */
interface InstructionPanelProps {
  app: string; // name of the tool (used for links and headings)
  description: string; // main description of what the tool does (supports Markdown)
  steps: InstructionStep[]; // ordered steps for using the tool
  defaultsDescription?: string; // optional explanation of default settings
}

/** Render Markdown paragraphs inline instead of <p> tags */
const stepComponent: Components = { p: ({ ...props }) => <span {...props} /> };

/**
 * InstructionPanel Component
 *
 * Displays a tool description, usage steps, optional default info,
 * and a privacy notice. Markdown formatting is supported in text fields.
 */
export default function InstructionPanel(props: InstructionPanelProps) {
  return (
    <div className="col-lg-5 mb-3 mb-lg-0 d-flex">
      <div className="p-4 bg-light border rounded flex-fill d-flex flex-column">
        {/* Section: What the tool does */}
        <h2 className="h4 mb-2">🛠️ What This Tool Does</h2>
        <ReactMarkdown>{props.description}</ReactMarkdown>

        {/* Section: How to use it */}
        <h3 className="h5 mb-2">📋 How to Use It</h3>
        <div className="steps">
          {props.steps.map((step, i) => {
            return (
              <div key={`step-${i}`}>
                <span className="icon">{step.icon}</span>
                <ReactMarkdown components={stepComponent}>{step.text}</ReactMarkdown>
              </div>
            );
          })}
          <p className="mt-2 small text-muted">
            For more detailed instructions, see the{" "}
            <a href={`/docs?tab=${props.app}`}>{props.app} documentation</a>.
          </p>
        </div>

        {/* Section: Defaults description */}
        {props.defaultsDescription && (
          <>
            <h3 className="h5 mb-2">ℹ️ About the Defaults</h3>
            <ReactMarkdown>{props.defaultsDescription}</ReactMarkdown>
          </>
        )}

        {/* Section: Privacy notice */}
        <p className="text-muted small mb-0">
          🔒 <strong>Privacy Notice:</strong> Your inputs are never stored. Only the output files
          generated by this tool are retained temporarily to facilitate downloads.
        </p>
      </div>
    </div>
  );
}
