services:
  web-scraper:
    container_name: node
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    working_dir: /app
