services:
  fly-box:
    container_name: node
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=3000
    working_dir: /app
    ports:
      - "${PORT}:3000"
      - "9229:9229"
