# TODO Update placeholder values when I figure out hosting
services:
  flybox:
    container_name: node
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./db:/app/db
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL="file:./db/dev.db"
    working_dir: /app
    ports:
      - "3000:3000"
    command: ["node", "server.js"]
