services:
  web-scraper:
    container_name: node
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - OLLAMA_URL=http://ollama:11434  # use service name, not 0.0.0.0
    working_dir: /app
    depends_on:
      - ollama

  ollama:
    container_name: ollama
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    # Start Ollama server and conditionally pull the model
    entrypoint: ["/bin/sh", "-c"]
    command: |
      # Start Ollama in the background
      ollama serve &
      
      # Wait for Ollama to start
      echo "Waiting for Ollama to start..."
      sleep 10
      
      # Check if the model exists and pull only if needed
      if ! ollama list | grep -q mixtral; then
        echo "Pulling mixtral model..."
        ollama pull mixtral
        echo "Mixtral model downloaded."
      else
        echo "Mixtral model already exists, skipping download."
      fi
      
      echo "Ollama is running with mixtral model ready!"
      wait
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep ollama | grep -v grep"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ollama:

