services:
  flybox:
    container_name: node
    build:
      context: ..
      dockerfile: ../Dockerfile
    volumes:
      - .:/app # syncs source code for live changes in dev
      - ./db:/app/db # persists SQLite dev.db outside container
    env_file:
      - ../.env
    working_dir: /app
    ports:
      - "${PORT}:3000"
      - "9229:9229"
