// List of URLs to scrape, UPDATED MAY 21, 2025
const sites = [
  {
    url: "https://bigskyanglers.com/",
    selector: "article",
    lastUpdated: "OCT 2024",
    keywords: ["fishing-reports", "report"],
    junkWords: ["news"],
    clickPhrases: ["Continue reading"],
  },
  {
    url: "http://henrysforkanglers.com/",
    selector: "article",
    lastUpdated: "MAY 2025",
    keywords: ["fishing-reports"],
    junkWords: [],
    clickPhrases: [],
  },
  {
    url: "https://www.thetackleshop.com/",
    selector: "article",
    lastUpdated: "MAY 2025",
    keywords: [
      "montana-fly-fishing-reports",
      "fishing-report",
      "fishing_report",
    ],
    junkWords: [],
    clickPhrases: [],
  },
  {
    url: "http://www.hatchfinders.com/",
    selector: "article",
    lastUpdated: "APR 2025",
    keywords: ["fishing-reports", "post"],
    junkWords: ["news"],
    clickPhrases: [],
  },
  {
    url: "https://snakeriverangler.com/",
    selector: "article",
    lastUpdated: "MAY 2025",
    keywords: [
      "fishing-reports",
      "fishing-report",
      // "snake-river-angler-fly-fishing-report"
    ],
    junkWords: [],
    clickPhrases: ["READ MORE"],
  },
  {
    url: "http://worldcastanglers.com/",
    selector: "article",
    lastUpdated: "MAY 2025",
    keywords: ["jackson-hole-fishing-report", "fishing-report"],
    junkWords: ["trip-report"],
    clickPhrases: ["Read more"],
  },
  {
    url: "http://www.montanaangler.com/",
    selector: "article",
    lastUpdated: "MAY 2025",
    keywords: ["montana-fishing-reports", "montana-fishing-report"],
    junkWords: [],
    clickPhrases: ["Read More"],
  },
  {
    url: "https://danbaileys.com/",
    selector: "article",
    lastUpdated: "MAY 2025",
    keywords: ["fishing-reports"],
    junkWords: [],
    clickPhrases: [],
  },
  {
    url: "https://bozemanflyfishing.com/",
    selector: "article",
    lastUpdated: "FEB 2025",
    keywords: ["fishing-reports"],
    junkWords: [],
    clickPhrases: [],
  },
  {
    url: "http://frontieranglers.com/",
    selector: "article",
    lastUpdated: "MAY 2025",
    keywords: ["fishing-reports", "fishing-report"],
    junkWords: [],
    clickPhrases: ["Read More"],
  },
  {
    url: "http://www.flyfishfood.com/",
    selector: "article",
    lastUpdated: "MAY 2025",
    keywords: ["idaho-yellowstone-fly-fishing-reports"],
    junkWords: [],
    clickPhrases: [],
  },
  {
    url: "https://bighornangler.com/",
    selector: "article",
    lastUpdated: "MAY 2025",
    keywords: ["reports", "fishing-report"],
    junkWords: [],
    clickPhrases: ["Read more"],
  },
  {
    url: "http://trroutfitters.com/",
    selector: "article",
    lastUpdated: "APR 2025",
    keywords: ["fishing-reports", "fishing-report"],
    junkWords: [],
    clickPhrases: [],
  },
  {
    url: "https://www.beartoothflyfishing.com/",
    selector: "div.post",
    lastUpdated: "MAY 2025",
    keywords: ["fishing-reports-tips", "fishing-reports", "fishing-report"],
    junkWords: [],
    clickPhrases: ["Continue reading"],
  },
  {
    url: "http://www.sweetwaterflyshop.com/",
    selector: "div.post",
    lastUpdated: "MAY 2025",
    keywords: ["fishing-reports"],
    junkWords: [],
    clickPhrases: ["Read More"],
  },
  {
    url: "http://snakeriverfly.com/",
    selector: "div.main-sidebar",
    lastUpdated: "MAY 2025",
    keywords: ["southeast-idaho-fishing-report"],
    junkWords: [],
    clickPhrases: [],
  },
  {
    url: "https://northforkanglers.com/",
    selector: "div.user-items-list",
    lastUpdated: "MAY 2025",
    keywords: ["fishing-reports"],
    junkWords: [],
    clickPhrases: [],
  },
  {
    url: "https://www.yellowdogflyfishing.com/",
    selector: "div.reportContent",
    lastUpdated: "MAY 2025",
    keywords: ["fishing-report", "fishing-reports"],
    junkWords: [],
    clickPhrases: [],
  },
  {
    url: "http://blackfootriver.com/",
    selector: "div.full-report",
    lastUpdated: "MAY 2025",
    keywords: ["fishing-reports"],
    junkWords: [],
    clickPhrases: [],
  },
  {
    url: "http://parksflyshop.com/",
    selector: "div.entry-content",
    lastUpdated: "2025",
    keywords: ["fishing-reports", "fishing_report"],
    junkWords: [],
    clickPhrases: [],
  },
  {
    url: "http://www.montanatrout.com/",
    selector: "main.page-blocks",
    lastUpdated: "MAY 2025",
    keywords: ["madison-river-fishing-report"],
    junkWords: [],
    clickPhrases: [],
  },
  {
    url: "http://www.sunriseflyshop.com/",
    selector: "ul.wp-block-latest-posts__list",
    lastUpdated: "MAY 2025",
    keywords: ["montana-fishing-reports"],
    junkWords: [],
    clickPhrases: [],
  },
  {
    url: "http://www.bozemanflysupply.com/",
    selector: 'div._1140-w-wrapper:has(h1:has-text("fishing report"))',
    lastUpdated: "MAY 2025",
    keywords: ["fishing-report", "river-report"],
    junkWords: [],
    clickPhrases: [],
  },
  {
    url: "https://theriversedge.com/",
    selector: 'div.container:has(h2:has-text("river fishing report"))',
    lastUpdated: "MAY 2025",
    keywords: ["montana-fishing-reports", "fishing-report"],
    junkWords: [],
    clickPhrases: ["View recent fishing reports"],
  },
  {
    url: "http://troutfitters.com/",
    selector: 'div.mb-5:has(h2:has-text("Fly Pattern Suggestions"))',
    lastUpdated: "MAY 2025",
    keywords: ["river-reports", "reports"],
    junkWords: [],
    clickPhrases: [],
  },
  {
    url: "http://madisonriveroutfitters.com/",
    selector: "div.container.main.content",
    lastUpdated: "MAY 2025",
    keywords: ["madison-river-fishing-reports", "fly-fishing-report"],
    junkWords: ["tagged"],
    clickPhrases: ["Read More"],
  },
  {
    url: "https://www.thestonefly.com/",
    selector: "div#main-content",
    lastUpdated: "2025",
    keywords: ["fishing-reports"],
    junkWords: [],
    clickPhrases: [],
  },
  {
    url: "http://westbankanglers.com/",
    selector: "main.main-content",
    lastUpdated: "MAY 2025",
    keywords: ["stream-reports"],
    junkWords: [],
    clickPhrases: ["Continue reading"],
  },
  {
    url: "http://www.mrfc.com/",
    selector: "main.main-content",
    lastUpdated: "MAY 2025",
    keywords: ["madison-river-fishing-report"],
    junkWords: [],
    clickPhrases: [],
  },
];

export { sites };
